apiVersion: v1               # используемая весрия API k8s
kind: Pod                    # создаем под
metadata:                    # дополнительные данные для идентификации
  name: vault                # имя пода
  labels:                    # метки пода
    app: vault               # метка
spec:                        # спецификация пода
  containers:                # список контейнеров в поде
  - name: vault              # имя контейнера
    image: vault:1.13.3      # запускаемый образ в контейнере
    ports:                   # желаемые порты
      - containerPort: 8200  # используемый порт в контейнере



#apiVersion: v1                  # используемая весрия API k8s
#kind: Deployment                # создаем объект развертывания 
#metadata:                       # дополнительные данные для идентификации
#  name: vault                   # имя объекта
#spec:                           # спецификация
#  selector:                     # чьи модули будут затронуты развертыванием
#    matchLabels:                # ко всем подам с app: vault
#      app: vault                # применить развертывание
#  template:                     # 
#    spec:                       # спецификация пода
#      containers:               # список контейнеров в поде
#        - name: vault           # имя контейнера
#          image: vault:1.13.3   # запускаемый образ в контейнере
#          ports:                # желаемые порты
#            containerPort: 8200 # используемый порт в контейнере