apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-react
  template:
    metadata:
      labels:
        app: app-react
    spec:
      containers:
        - name: app-react
          image: ifilyaninitmo/itdt-contained-frontend:master
          envFrom:
            - configMapRef:
                name: config-map

---

apiVersion: v1
kind: Service
metadata:
  name: balancer-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: app-react
