apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-deployment
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
        - name: app-react
          image: ifilyaninitmo/itdt-contained-frontend:master
          env:
            - name:  REACT_APP_USERNAME
              value: 'qveex'
            - name:  REACT_APP_COMPANY_NAME
              value: 'itmo'
          ports:
            - name: container-port
              containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: app-deployment
  ports:
  - port: 2000
    targetPort: container-port