apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: replica-set-react
  template:
    metadata:
      labels:
        app: replica-set-react
    spec:
      containers:
        - name: app-react
          image: ifilyaninitmo/itdt-contained-frontend:master
          envFrom:
            - configMapRef:
                name: config-map

---

apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: replica-set-react
